In [45]:
import numpy as np
from helpers import load_csv_data
import matplotlib.pyplot as plt




In [58]:


x_train, x_test, y_train, train_ids, test_ids = load_csv_data("C:\\Users\\Laissy Aurélien\\Desktop\\project-1-ML\\dataset_to_release", sub_sample=True)
print(x_test.shape)
print(x_train.shape)

(109379, 321)
(109379, 321)


In [59]:
"""Data cleaning """
from data_processing import * 

x_train = clean_all(x_train)
x_test = clean_all(x_test)


#there is a difference of the number of columns after the data cleaning for x_test and x_train which causes troubles when we wanna compute ypred = x_test dot w 



(6563, 256)
(6563, 256)
(6563, 160)
(6563, 160)
(6563, 160)
(6563, 160)


c:\Users\Laissy Aurélien\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\Laissy Aurélien\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


(6563, 84)
(109379, 256)
(109379, 256)
(109379, 160)
(109379, 160)
(109379, 160)
(109379, 160)
(109379, 91)


In [49]:
# -*- coding: utf-8 -*-
"""Exercise 3.

Ridge Regression
"""


def ridge_regression(y, tx, lambda_):
    """Implement ridge regression.

    Args:
        y: numpy array of shape (N,), N is the number of samples.
        tx: numpy array of shape (N, D), D is the number of features.
        lambda_: scalar.

    Returns:
        w: optimal weights, numpy array of shape (D, ), D is the number of features.
        loss: loss mse value (scalar)

    >>> ridge_regression(np.array([0.1, 0.2]), np.array([[2.3, 3.2], [1.0, 0.1]]), 0)
    array([ 0.21212121, -0.12121212])
    >>> ridge_regression(np.array([0.1, 0.2]), np.array([[2.3, 3.2], [1.0, 0.1]]), 1)
    array([0.03947092, 0.00319628])
    """
    
    l = 2 * tx.shape[0] * lambda_ * np.identity(tx.shape[1])
    w = np.linalg.solve(tx.T @ tx + l, tx.T @ y)
    loss = compute_mse(y, tx, w) #was compute_loss in lab 3
    
    return w #,loss


# -*- coding: utf-8 -*-
"""a function of ploting figures."""
import numpy as np
import matplotlib.pyplot as plt


def cross_validation_visualization(lambds, rmse_tr, rmse_te):
    """visualization the curves of rmse_tr and rmse_te."""
    plt.semilogx(lambds, rmse_tr, marker=".", color="b", label="train error")
    plt.semilogx(lambds, rmse_te, marker=".", color="r", label="test error")
    plt.xlabel("lambda")
    plt.ylabel("r mse")
    # plt.xlim(1e-4, 1)
    plt.title("cross validation")
    plt.legend(loc=2)
    plt.grid(True)
    plt.savefig("cross_validation")


def bias_variance_decomposition_visualization(degrees, rmse_tr, rmse_te):
    """visualize the bias variance decomposition."""
    rmse_tr_mean = np.expand_dims(np.mean(rmse_tr, axis=0), axis=0)
    rmse_te_mean = np.expand_dims(np.mean(rmse_te, axis=0), axis=0)
    plt.plot(degrees, rmse_tr.T, linestyle="-", color=([0.7, 0.7, 1]), linewidth=0.3)
    plt.plot(degrees, rmse_te.T, linestyle="-", color=[1, 0.7, 0.7], linewidth=0.3)
    plt.plot(degrees, rmse_tr_mean.T, "b", linestyle="-", label="train", linewidth=3)
    plt.plot(degrees, rmse_te_mean.T, "r", linestyle="-", label="test", linewidth=3)
    plt.xlim(1, 9)
    plt.ylim(0.2, 0.7)
    plt.xlabel("degree")
    plt.ylabel("error")
    plt.legend(loc=1)
    plt.title("Bias-Variance Decomposition")
    plt.savefig("bias_variance")

# -*- coding: utf-8 -*-
"""some helper functions."""

import numpy as np


def load_data():
    """load data."""
    data = np.loadtxt("dataEx3.csv", delimiter=",", skiprows=1, unpack=True)
    x = data[0]
    y = data[1]
    return x, y

# -*- coding: utf-8 -*-
"""A function to compute the cost."""

import numpy as np
# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.15.1
#   kernelspec:
#     display_name: Python3
#     language: python
#     name: python3
# ---

import numpy as np
#from functions import sigmoid

def calculate_mse(e):
    """Calculate the mse for vector e."""
    return np.mean(e**2) / 2


def calculate_mae(e):
    """Calculate the mae for vector e."""
    return np.mean(np.abs(e))


def calculate_logloss(y_true, y_pred, eps=1e-8):
    """Calculate the logloss"""
    return -np.mean(
        y_true * np.log(y_pred + eps) + (1 - y_true) * np.log(1 - y_pred + eps)
    )



def compute_loss(y, tx, w, loss_type):
    """Calculate the loss using either MSE or MAE.

    Args:
        y: shape=(N, )
        tx: shape=(N,2)
        w: shape=(2,). The vector of model parameters.
        loss_type: string in ["mae", "mse", "log"] specifying the type of loss to compute

    Returns:
        the value of the loss (a scalar), corresponding to the input parameters w.
    """
    print(type(y))
    print(type(tx))
    print(type(tx))
    e = y -tx.dot(w)

    if loss_type == "mse":
        return calculate_mse(e)

    elif loss_type == "mae":
        return calculate_mae(e)

    elif loss_type == "log":
        y_pred = sigmoid(tx @ w)
        return calculate_logloss(y, y_pred)

    else:
        raise ValueError(
            "Invalid value for argument 'loss_type' when calling compute_loss, 'type' must be in ['mse', 'mae', 'log']."
        )




def compute_mse(y, tx, w):
    """compute the loss by mse.
    Args:
        y: numpy array of shape (N,), N is the number of samples.
        tx: numpy array of shape (N,D), D is the number of features.
        w: weights, numpy array of shape(D,), D is the number of features.

    Returns:
        mse: scalar corresponding to the mse with factor (1 / 2 n) in front of the sum

    >>> compute_mse(np.array([0.1,0.2]), np.array([[2.3, 3.2], [1., 0.1]]), np.array([0.03947092, 0.00319628]))
    0.006417022764962313
    """

    e = y - tx.dot(w)
    mse = e.dot(e) / (2 * len(e))
    return mse

# -*- coding: utf-8 -*-
"""implement a polynomial basis function."""

import numpy as np

def build_poly(x, degree):
    """
    Polynomial basis functions for input data x.

    Args:
        x: numpy array of shape (N, D), where N is the number of samples, and D is the number of features.
        degree: integer, the degree of the polynomial basis.

    Returns:
        poly: numpy array of shape (N, D * (degree + 1)), representing the extended feature matrix.
    """
    
    N, D = x.shape
    poly = np.ones((N, D * (degree + 1)))

    for d in range(1, degree + 1):
        poly[:, D*d:D*(d+1)] = x ** d

    return poly

def build_k_indices(y, k_fold, seed):
    """build k indices for k-fold.

    Args:
        y:      shape=(N,)
        k_fold: K in K-fold, i.e. the fold num
        seed:   the random seed

    Returns:
        A 2D array of shape=(k_fold, N/k_fold) that indicates the data indices for each fold

    >>> build_k_indices(np.array([1., 2., 3., 4.]), 2, 1)
    array([[3, 2],
           [0, 1]])
    """
    num_row = y.shape[0]
    interval = int(num_row / k_fold)
    np.random.seed(seed)
    indices = np.random.permutation(num_row)
    k_indices = [indices[k * interval : (k + 1) * interval] for k in range(k_fold)]
    return np.array(k_indices)



In [50]:
def cross_validation(y, x, k_indices, k, lambda_, degree):
    """return the loss of ridge regression for a fold corresponding to k_indices

    Args:
        y:          shape=(N,)
        x:          shape=(N,)
        k_indices:  2D array returned by build_k_indices()
        k:          scalar, the k-th fold (N.B.: not to confused with k_fold which is the fold nums)
        lambda_:    scalar, cf. ridge_regression()
        degree:     scalar, cf. build_poly()

    Returns:
        train and test root mean square errors rmse = sqrt(2 mse)

    >>> cross_validation(np.array([1.,2.,3.,4.]), np.array([6.,7.,8.,9.]), np.array([[3,2], [0,1]]), 1, 2, 3)
    (0.019866645527597114, 0.33555914361295175)
    """
    
    ### SOLUTION
    # get k'th subgroup in test, others in train
    te_indice = k_indices[k]
    tr_indice = k_indices[~(np.arange(k_indices.shape[0]) == k)]
    tr_indice = tr_indice.reshape(-1)
    y_te = y[te_indice]
    y_tr = y[tr_indice]
    x_te = x[te_indice]
    x_tr = x[tr_indice]
    
    # form data with polynomial degree
    tx_tr = build_poly(x_tr, degree)
    tx_te = build_poly(x_te, degree)
    # ridge regression
    w = ridge_regression(y_tr, tx_tr, lambda_)
    # calculate the loss for train and test data
    loss_tr = np.sqrt(2 * compute_loss(y_tr, tx_tr, w, "mse"))
    loss_te = np.sqrt(2 * compute_loss(y_te, tx_te, w, "mse"))

    return loss_tr, loss_te


In [51]:
def best_degree_selection(degrees, k_fold, lambdas, seed=1):
    """Cross-validation over regularization parameter lambda and degree.
    
    Args:
        degrees: shape=(d,), where d is the number of degrees to test
        k_fold: integer, the number of folds
        lambdas: shape=(p,), where p is the number of values of lambda to test
        seed: integer, random seed
    
    Returns:
        best_degree : integer, value of the best degree
        best_lambda : scalar, value of the best lambda
        best_rmse : value of the rmse for the couple (best_degree, best_lambda)
    """
    k_indices = build_k_indices(y_train, k_fold, seed)

    best_lambdas = np.zeros((len(degrees), len(lambdas)))
    best_rmses = np.zeros((len(degrees), len(lambdas)))

    for i, degree in enumerate(degrees):
        for j, lambda_ in enumerate(lambdas):
            rmse_te = []
            for k in range(k_fold):
                _, loss_te = cross_validation(y_train, x_train, k_indices, k, lambda_, degree)
                rmse_te.append(loss_te)
            best_lambdas[i, j] = lambda_
            best_rmses[i, j] = np.mean(rmse_te)

    ind_best_degree, ind_best_lambda = np.unravel_index(np.argmin(best_rmses), best_rmses.shape)
    best_degree = degrees[ind_best_degree]
    best_lambda = lambdas[ind_best_lambda]
    best_rmse = best_rmses[ind_best_degree, ind_best_lambda]

    return best_degree, best_lambda, best_rmse, best_lambdas, best_rmses


In [52]:
# can lead to a numerical error if you use an older version than Python 3.9
#test(best_degree_selection)

#best_degree, best_lambda, best_rmse = best_degree_selection(
 #   np.arange(2, 11), 4, np.logspace(-4, 0, 30)
#)
#print(
 #   "The best rmse of %.3f is obtained for a degree of %.f and a lambda of %.5f."
 #   % (best_rmse, best_degree, best_lambda)
#)

import numpy as np
import matplotlib.pyplot as plt
from decimal import Decimal

# Sample degrees and lambdas for visualization
degrees = np.arange(2, 11)
lambdas = np.logspace(-4, 0, 30)
seed = 1

best_degree, best_lambda, best_rmse, best_lambdas, best_rmses = best_degree_selection(
    degrees, k_fold=4, lambdas=lambdas, seed=seed
)
print(
    "The best RMSE of %.3f is obtained for a degree of %.f and a lambda of %.5f."
    % (best_rmse, best_degree, best_lambda)
)



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.nd

In [53]:
tx_tr=build_poly(x_train, best_degree)

wrr = ridge_regression(y_train, tx_tr, best_lambda)
print(wrr.shape)


(420,)


In [54]:
"""fonction sigmoid pour optimiser la probabilité que la rep soit vraie"""
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [55]:
"""prédire le y"""

tx_te=build_poly(x_test, best_degree)

"""méthode avec la probabilité"""

y_pred_prob= np.dot(tx_te,wrr)
y_pred_prob= sigmoid(y_pred_prob)
y_pred_prob[sigmoid(y_pred_prob) > 0.5] = 1
y_pred_prob[sigmoid(y_pred_prob) <= 0.5] = -1


"""méthode simple"""
y_pred= np.dot(tx_te,wrr)

y_pred[y_pred < 0] = -1
y_pred[y_pred >= 0] = 1
print(y_pred)

ValueError: shapes (109379,455) and (420,) not aligned: 455 (dim 1) != 420 (dim 0)

In [ ]:
"""calculer le f1 score"""


def compute_f1_score(y_true, y_pred):
    tp = np.sum((y_pred == 1) & (y_pred == y_true))
    fp = np.sum((y_pred == 1) & (y_pred != y_true))
    fn = np.sum((y_pred == 0) & (y_pred != y_true))
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1_score = 2 * (precision * recall) / (precision + recall)
    return f1_score

#for the simple prediction
f1_score_simp= compute_f1_score(y_te, y_pred)
print("f1_score_simp")
print(f1_score_simp)

#for the probabilities prediction
f1_score_prob= compute_f1_score(y_te, y_pred_prob)
print("f1_score_prob")
print(f1_score_prob)




In [ ]:
"""calculer l'accuracy"""
def compute_accuracy(y_te, y_pred):
    return np.mean(y_te == y_pred)

accuracy_simp = compute_accuracy(y_te, y_pred)
print("accuracy_simp is %.3f" % accuracy_simp)

accuracy_prob = compute_accuracy(y_te, y_pred_prob)
print("accuracy_prob is %.3f" % accuracy_prob)






In [ ]:
"""créer la submission de y_pred"""

create_csv_submission(ids_pred, y_pred, "submission.csv")
print("Submission saved at 'data/submission.csv'.")
